### ISSUE TITLE
Enable Search - Discussion

### ISSUE THREAD

**Issue by meilisss** [TheArcadiaGroup/casper-info-api#17]
## 1st APPROACH
Actually, this functionality should be implemented as one search function will be triggered through only one unique endpoint such as `/v1/:address/search` or `/v1/search/:address` can be implemented in all pages of FE search box form. So, I see from this case the sub-tasks flow below:

### Tasks:
- [ ] Create an endpoint `/v1/search/:address`
- [ ] Create an `search` controller for that and place search funcionality logic there.
- [ ] According search address type and its result response should redirect to its specific route. For example: if search phrase is `account public key` then `/v1/search/:accountPublicKey` route will redirect to `/v1/accounts/:accountPublicKey` as well as block hash, account hash, validator key and etc.

## 2nd APPROACH

Thish search functionality logic can placed in one util function such as `utils/searchAddress.ts` and it returns only what kind of data has found from our db with its type and value such as:
```json
{
  type: 'blocks',
  value: {
    [  
      {
        "_id": "6332d1c91608d9309352aa30",
        "deployHash": "ffb4de6ea3a0419651d70a4b4dcf3a02272350410a748dc1b641047918400484",
        "amount": 0,
        "blockHash": "d0371fb9f39bc634dc04f6c0381b21cffc4f931cafd9e52c60fc88f1b8b3d99a",
        "cost": 0.6362731,
        "deployType": "deploy",
        "entryPoint": "WASM Deploy",
        "fromAccountHash": "",
        "publicKey": "010d565ed2f2efcbda741fc3f14f19d6dd72c324b27b2f584825fc1685469d545d",
        "status": "fail",
        "timestamp": "2022-09-27T05:28:11.625Z",
        "toAccountHash": "",
        "validator": ""
      }
    ]
  }
}
```
then we can make redirection according to that functions returned type and value.

### Tasks:
- [ ] Create an endpoint `/v1/search/:address`
- [ ] Create an `search` controller for that and pass `address` into search util function.
- [ ] According to search util function's result make redirection such as: 
```ts
  res.redirect(`/v1/${result.type}/${result.value}`);
```

**_Please, feel free to ask any questions or give suggestions._**
